version: "3.8"

services:    
  stock-api:
    image: 'ghcr.io/ozon-edu-csharp-2021/stock-api:main'
    hostname: stock_api
    depends_on:
    - "supply-service"
    ports:
      - "8040:80"

  emailing-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/emailing-service:main'
    hostname: emailing_service
    ports:
      - "8041:80"

  employees-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/employees-service:main'
    hostname: employees_service
    ports:
      - "8042:80"

  supply-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/supply-service:main'
    hostname: supply_service
    ports:
      - "8043:80"

  merchandise-service:
    build: ..
    hostname: merchandise_service
    depends_on:
      - "stock-api"
    ports:
      - "8044:80"



       
 
      